---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: hardik5k/calculator:latest
        source: pull
    - name: Creating container
      shell: docker create --name Calculator hardik5k/calculator
